version: '2'

services:
    vault:
        image: vault
        cap_add: 
            - IPC_LOCK
        networks: 
            - secrets

    #Build application docker image
    go-microservice:
        build:
            context: .
        ports:
            - "80:80"
        networks: 
            - secrets
        links:
            - vault

networks:
    secrets:
        driver: bridge